package model;

import java.io.*;
import java.util.Properties;

public class ConfigStore {
	private File configFile;
	private Properties properties;

	public ConfigStore() {

		try {

			this.configFile = new File(System.getProperty("user.home")
					+ "/.peeter/config.properties");
			boolean fileIsNew = false;

			if (!this.configFile.isFile()) {
				fileIsNew = true;
				// Create File if not exists
				this.configFile.getParentFile().mkdirs();
				this.configFile.createNewFile();
			}

			this.properties = new Properties();
			this.properties.load(new FileInputStream(this.configFile
					.getAbsoluteFile()));

			if (fileIsNew) {
				// Set Default Data in Config File
				this.properties.setProperty("locale.language", "de");
				this.properties.setProperty("locale.country", "DE");
			}

		} catch (IOException e) {
			// TODO: Handle exception
			e.printStackTrace();
		}
	}

	public String get(String name) {
		try {
			this.properties.load(new FileInputStream(this.configFile
					.getAbsoluteFile()));
		} catch (IOException e) {
			e.printStackTrace();
		}

		return this.properties.getProperty(name);
	}

	public void set(String name, String value) {
		try {

			this.properties.setProperty(name, value);
			this.properties.store(
					new FileOutputStream(this.configFile.getAbsoluteFile()),
					"Auto generated by Peeter");

		} catch (FileNotFoundException e) {
			// TODO: Handle exception
			e.printStackTrace();
		} catch (IOException e) {
			// TODO: Handle exception
			e.printStackTrace();
		}
	}

	public void unset(String name) {
		try {
			this.properties.remove(name);
			this.properties.store(
					new FileOutputStream(this.configFile.getAbsoluteFile()),
					"Auto generated by Peeter");
		} catch (IOException e) {
			// TODO: Handle exception
			e.printStackTrace();
		}
	}
}
