import java.io.*;
import java.util.Properties;

public class ConfigStore {
    private File configFile;
    private Properties properties;

    public ConfigStore() {

        try {

            this.configFile = new File(System.getProperty("user.home") + "/.peeter/config.properties");

            if (!this.configFile.isFile()) {
                // Create File if not exists
                this.configFile.getParentFile().mkdirs();
                this.configFile.createNewFile();
            }

            this.properties = new Properties();

            this.properties.load(new FileInputStream(this.configFile.getAbsoluteFile()));

        } catch (IOException e) {
            // TODO: Handle exception
            e.printStackTrace();
        }
    }

    public String get(String name) {
        return this.properties.getProperty(name);
    }

    public void set(String name, String value) {
        try {

            this.properties.setProperty(name, value);
            this.properties.store(new FileOutputStream(this.configFile.getAbsoluteFile()), "Auto generated by Peeter");

        } catch (FileNotFoundException e) {
            // TODO: Handle exception
            e.printStackTrace();
        } catch (IOException e) {
            // TODO: Handle exception
            e.printStackTrace();
        }
    }

    public void unset(String name) {
        try {
            this.properties.remove(name);
            this.properties.store(new FileOutputStream(this.configFile.getAbsoluteFile()), "Auto generated by Peeter");
        } catch (IOException e) {
            // TODO: Handle exception
            e.printStackTrace();
        }
    }
}
